package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

// TestEndToEndProvisioning exercises the tmux client against a real tmux server
// on a throwaway socket. It is skipped when tmux is not installed. Unlike the
// rest of the suite (which fakes the command factory), this test issues real
// tmux commands and parses real tmux output, guarding the parts most likely to
// drift against new tmux versions: output formats, base-index logic, and the
// wait-for synchronisation.
func TestEndToEndProvisioning(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	socket := fmt.Sprintf("glaze-e2e-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	// Ensure the throwaway server is always torn down.
	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	dir := t.TempDir()

	session, err := client.NewSession("e2e", dir)
	assert.NoError(t, err)
	assert.NotNil(t, session)
	assert.Equal(t, "e2e", session.Name)

	running, err := client.IsRunning()
	assert.NoError(t, err)
	assert.True(t, running)
	assert.True(t, hasSession(t, client, "e2e"))

	// Session-scoped option round-trips through tmux.
	assert.NoError(t, session.SetOption("history-limit", "4242"))
	option, err := client.GetOption(session.Target(), "history-limit", "session")
	assert.NoError(t, err)
	assert.Contains(t, option, "4242")

	// Create a window with its own starting directory and split it.
	windowDir := t.TempDir()
	window, err := session.NewWindow("editor", windowDir)
	assert.NoError(t, err)
	assert.Equal(t, "editor", window.Name)

	windows, err := client.Windows(session)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(windows, func(w *Window) bool {
		return w.Name == "editor"
	}))

	defaultPane, err := firstPaneOf(client, window)
	assert.NoError(t, err)
	assert.NotNil(t, defaultPane)
	// The window's default pane should inherit the window's starting directory.
	// tmux reports the symlink-resolved path, so compare against that.
	resolvedDir, err := filepath.EvalSymlinks(windowDir)
	assert.NoError(t, err)
	assert.Equal(t, resolvedDir, defaultPane.StartingDirectory)

	pane, err := window.Split(defaultPane.Target(), "shell", dir)
	assert.NoError(t, err)
	assert.Equal(t, "shell", pane.Name)

	panes, err := client.Panes(window)
	assert.NoError(t, err)
	assert.Equal(t, 2, len(panes))

	// Run must return only after every command but the last has finished, so the marker exists at once.
	runner, err := client.NewCommandRunner(0)
	assert.NoError(t, err)

	marker := filepath.Join(dir, "done.marker")
	runWithTimeout(t, 10*time.Second, func() error {
		return runner.Run(pane.Target(), []string{fmt.Sprintf("touch '%s'", marker), "true"})
	})
	assert.FileExists(t, marker)

	// Tear the session down explicitly and confirm it is gone.
	assert.NoError(t, client.KillSessionByName("e2e"))
	assert.False(t, hasSession(t, client, "e2e"))
}

// TestEndToEndHostileNames creates a session, window and pane with names that
// tmux escapes in -F output and reads each name back. It guards the q: formats
// and the splitter against the tmux version under test. tmux 3.4 escapes a $
// that starts a variable name a second time, so run it on 3.4 as well.
func TestEndToEndHostileNames(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	socket := fmt.Sprintf("glaze-e2e-names-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	// TestEndToEndRewrittenNames covers the characters that glaze replaces.
	const (
		sessionName = `s;1 x;`
		windowName  = `w;1 $HOME;`
		paneName    = `p;1 ${x};`
	)

	session, err := client.NewSession(sessionName, t.TempDir())
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, sessionName, session.Name)

	found, err := client.FindSessionByName(sessionName)
	if assert.NoError(t, err) {
		assert.Equal(t, session.Id, found.Id)
	}

	// No client is attached, so tmux reports the only session on the server.
	current, err := client.CurrentSession()
	if assert.NoError(t, err) {
		assert.Equal(t, sessionName, current.Name)
	}

	window, err := session.NewWindow(windowName, "")
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, windowName, window.Name)

	windows, err := client.Windows(session)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(windows, func(w *Window) bool {
		return w.Name == windowName
	}), "window name did not round-trip")

	defaultPane, err := firstPaneOf(client, window)
	if !assert.NoError(t, err) {
		return
	}

	_, err = window.Split(defaultPane.Target(), paneName, "")
	assert.NoError(t, err)

	panes, err := client.Panes(window)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(panes, func(p *Pane) bool {
		return p.Name == paneName
	}), "pane name did not round-trip")
}

// TestEndToEndRewrittenNames uses names that tmux would rewrite. A session must be found
// and killed again by the name glaze was given, and window and pane names come back sanitised.
func TestEndToEndRewrittenNames(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	socket := fmt.Sprintf("glaze-e2e-rewrite-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	for _, name := range []string{"a.b", "a:b", `a\b`, "p$x", "p${x}", "tab\tx"} {
		t.Run(name, func(t *testing.T) {
			session, err := client.NewSession(name, t.TempDir())
			if !assert.NoError(t, err) {
				return
			}

			assert.True(t, hasSession(t, client, name), "has-session with the requested name")

			found, err := client.FindSessionByName(name)
			if assert.NoError(t, err) {
				assert.Equal(t, session.Id, found.Id)
			}

			assert.NoError(t, client.KillSessionByName(name))
			assert.False(t, hasSession(t, client, name), "session still running after kill")
		})
	}

	session, err := client.NewSession("names", t.TempDir())
	if !assert.NoError(t, err) {
		return
	}

	window, err := session.NewWindow("w\\z\tq", "")
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, "w-z-q", window.Name)

	windows, err := client.Windows(session)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(windows, func(w *Window) bool {
		return w.Name == "w-z-q"
	}), "sanitised window name did not round-trip")

	defaultPane, err := firstPaneOf(client, window)
	if !assert.NoError(t, err) {
		return
	}

	pane, err := window.Split(defaultPane.Target(), "p\\z\tq", "")
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, "p-z-q", pane.Name)

	panes, err := client.Panes(window)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(panes, func(p *Pane) bool {
		return p.Name == "p-z-q"
	}), "sanitised pane title did not round-trip")
}

// TestEndToEndNonASCIINamesUnderCLocale reads non-ASCII names back while the
// tmux client runs under a non-UTF-8 locale.
func TestEndToEndNonASCIINamesUnderCLocale(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	t.Setenv("LANG", "C")
	t.Setenv("LC_ALL", "C")
	t.Setenv("LC_CTYPE", "C")

	socket := fmt.Sprintf("glaze-e2e-locale-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	session, err := client.NewSession("café", t.TempDir())
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, "café", session.Name)

	found, err := client.FindSessionByName("café")
	if assert.NoError(t, err) {
		assert.Equal(t, session.Id, found.Id)
	}

	window, err := session.NewWindow("naïve", "")
	if !assert.NoError(t, err) {
		return
	}

	windows, err := client.Windows(session)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(windows, func(w *Window) bool {
		return w.Name == "naïve"
	}), "window name did not round-trip")

	defaultPane, err := firstPaneOf(client, window)
	if !assert.NoError(t, err) {
		return
	}

	_, err = window.Split(defaultPane.Target(), "ünï", "")
	assert.NoError(t, err)

	panes, err := client.Panes(window)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(panes, func(p *Pane) bool {
		return p.Name == "ünï"
	}), "pane name did not round-trip")
}

// TestEndToEndFormatSequencesInNames checks that tmux keeps #{...} and #X in
// names, titles and directories literally instead of expanding them.
func TestEndToEndFormatSequencesInNames(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	socket := fmt.Sprintf("glaze-e2e-format-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	dir := filepath.Join(t.TempDir(), "d#{session_name}")
	assert.NoError(t, os.Mkdir(dir, 0o750))
	resolvedDir, err := filepath.EvalSymlinks(dir)
	assert.NoError(t, err)

	session, err := client.NewSession("s#{host_short}", dir)
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, "s#{host_short}", session.Name)
	assert.True(t, hasSession(t, client, "s#{host_short}"))

	window, err := session.NewWindow("w#{session_name} a#Sb #[fg=red]x", dir)
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, "w#{session_name} a#Sb #[fg=red]x", window.Name)

	defaultPane, err := firstPaneOf(client, window)
	if !assert.NoError(t, err) {
		return
	}
	assert.Equal(t, resolvedDir, defaultPane.StartingDirectory)

	pane, err := window.Split(defaultPane.Target(), "p#{pane_id}", dir)
	if !assert.NoError(t, err) {
		return
	}
	splitDir, err := filepath.EvalSymlinks(pane.StartingDirectory)
	assert.NoError(t, err)
	assert.Equal(t, resolvedDir, splitDir)

	panes, err := client.Panes(window)
	assert.NoError(t, err)
	assert.True(t, slices.ContainsFunc(panes, func(p *Pane) bool {
		return p.Name == "p#{pane_id}"
	}), "pane title did not round-trip")
}

// TestEndToEndCommandRunner runs commands that a line editor or the tmux argument parser would change.
// It uses the default shell of the machine, so each developer and CI runner tests a different shell.
func TestEndToEndCommandRunner(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	socket := fmt.Sprintf("glaze-e2e-runner-%d", os.Getpid())

	client, err := NewClient("", socket, discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	t.Cleanup(func() {
		// The socket name is generated by this test, not user input.
		_ = exec.Command("tmux", "-L", socket, "kill-server").Run() //nolint:gosec // G204
	})

	dir := t.TempDir()
	session, err := client.NewSession("runner", dir)
	assert.NoError(t, err)

	window, err := session.NewWindow("w", dir)
	assert.NoError(t, err)

	pane, err := firstPaneOf(client, window)
	assert.NoError(t, err)

	t.Run("runs each command as written", func(t *testing.T) {
		runner, err := client.NewCommandRunner(0)
		assert.NoError(t, err)

		out := filepath.Join(dir, "out")
		commands := []string{
			"sleep 1 &",
			"echo wow!x > " + out + ";",
			// A real tab and a real newline, which a line editor would complete or split.
			"printf 'a\tb\n' >> " + out + " # a comment",
			"-x 2>/dev/null; echo dash >> " + out,
			"echo " + strings.Repeat("A", 5000) + " >> " + out,
			"echo end >> " + out,
		}
		runWithTimeout(t, 10*time.Second, func() error {
			return runner.Run(pane.Target(), commands)
		})

		// The last command runs after Run returns.
		want := "wow!x\na\tb\ndash\n" + strings.Repeat("A", 5000) + "\nend\n"
		assert.Eventually(t, func() bool {
			got, _ := os.ReadFile(out) //nolint:gosec // G304: the path is in a test directory.
			return string(got) == want
		}, 10*time.Second, 50*time.Millisecond)

		buffers, err := exec.Command("tmux", "-L", socket, "list-buffers").Output() //nolint:gosec // G204
		assert.NoError(t, err)
		assert.Empty(t, string(buffers))
	})

	t.Run("runs the commands after a syntax error", func(t *testing.T) {
		runner, err := client.NewCommandRunner(0)
		assert.NoError(t, err)

		out := filepath.Join(dir, "after")
		runWithTimeout(t, 10*time.Second, func() error {
			return runner.Run(pane.Target(), []string{"if then", `echo "unclosed`, "echo after > " + out, "true"})
		})
		assert.FileExists(t, out)
	})

	t.Run("stops waiting when the shell exits", func(t *testing.T) {
		exiting, err := window.Split(pane.Target(), "exiting", dir)
		assert.NoError(t, err)

		runner, err := client.NewCommandRunner(0)
		assert.NoError(t, err)

		done := make(chan error, 1)
		go func() { done <- runner.Run(exiting.Target(), []string{"exit", "true"}) }()

		select {
		case err := <-done:
			assert.ErrorIs(t, err, ErrPaneExited)
		case <-time.After(10 * time.Second):
			t.Fatal("Run did not return after the shell exited")
		}
	})

	t.Run("stops waiting after the timeout", func(t *testing.T) {
		runner, err := client.NewCommandRunner(200 * time.Millisecond)
		assert.NoError(t, err)

		done := make(chan error, 1)
		go func() { done <- runner.Run(pane.Target(), []string{"sleep 5", "true"}) }()

		select {
		case err := <-done:
			assert.ErrorIs(t, err, ErrCommandTimeout)
		case <-time.After(10 * time.Second):
			t.Fatal("Run did not return after the timeout")
		}
	})
}

// TestEndToEndUnreachableServer checks that a socket glaze cannot open is not reported as a missing session.
func TestEndToEndUnreachableServer(t *testing.T) {
	if _, err := exec.LookPath("tmux"); err != nil {
		t.Skip("tmux is not installed; skipping end-to-end test")
	}

	if os.Geteuid() == 0 {
		t.Skip("root ignores directory permissions, so the socket stays reachable")
	}

	// A socket path must be short, and the macOS temp directory is too long.
	dir, err := os.MkdirTemp("/tmp", "glaze-e2e-")
	assert.NoError(t, err)
	socket := filepath.Join(dir, "sock")

	client, err := NewClient(socket, "", discardLogger)
	if err != nil {
		t.Fatalf("could not create client: %v", err)
	}

	_, err = client.NewSession("held", t.TempDir())
	assert.NoError(t, err)

	t.Cleanup(func() {
		_ = os.Chmod(dir, 0o700) //nolint:gosec // G302: the test restores its own directory.
		// The socket path is generated by this test, not user input.
		_ = exec.Command("tmux", "-S", socket, "kill-server").Run() //nolint:gosec // G204
		_ = os.RemoveAll(dir)
	})

	assert.NoError(t, os.Chmod(dir, 0o000))

	exists, err := client.HasSession("held")
	assert.False(t, exists)
	assert.ErrorIs(t, err, ErrUnreachable)
	assert.ErrorContains(t, err, "Permission denied")

	running, err := client.IsRunning()
	assert.False(t, running)
	assert.ErrorIs(t, err, ErrUnreachable)

	// With access again, the same session is found.
	assert.NoError(t, os.Chmod(dir, 0o700)) //nolint:gosec // G302: the test restores its own directory.
	assert.True(t, hasSession(t, client, "held"))
}

// hasSession reports whether the session exists and fails the test when tmux cannot answer.
func hasSession(t *testing.T, client *Client, name string) bool {
	t.Helper()

	exists, err := client.HasSession(name)
	assert.NoError(t, err)

	return exists
}

// firstPaneOf returns the base-index pane of the given window.
func firstPaneOf(client *Client, window *Window) (*Pane, error) {
	panes, err := client.Panes(window)
	if err != nil {
		return nil, err
	}

	if len(panes) == 0 {
		return nil, fmt.Errorf("no pane found for window %q", window.Name)
	}

	return slices.MinFunc(panes, func(x, y *Pane) int { return int(x.Id) - int(y.Id) }), nil
}

// runWithTimeout fails the test if fn does not return within d, preventing a
// hung wait-for from stalling the whole suite.
func runWithTimeout(t *testing.T, d time.Duration, fn func() error) {
	t.Helper()
	done := make(chan error, 1)
	go func() { done <- fn() }()

	select {
	case err := <-done:
		assert.NoError(t, err)
	case <-time.After(d):
		t.Fatalf("operation did not complete within %s", d)
	}
}
