# Test image for the glaze release binary on Alpine (musl).
FROM alpine:3.22
ARG GLAZE_VERSION=v0.1.6
ARG TARGETARCH
RUN apk add --no-cache tmux curl unzip bash coreutils util-linux-misc procps findutils
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
WORKDIR /opt/glaze
RUN curl -fsSLO https://github.com/wilhelm-murdoch/glazier/releases/download/${GLAZE_VERSION}/glaze-linux-${TARGETARCH}.zip \
 && curl -fsSLO https://github.com/wilhelm-murdoch/glazier/releases/download/${GLAZE_VERSION}/SHA256SUMS \
 && sha256sum -c SHA256SUMS --ignore-missing \
 && unzip -o glaze-linux-${TARGETARCH}.zip
